package com.landportal.entity;
public enum CaseStatus { IDENTIFIED, PRELIMINARY_NOTICE, SURVEY_IN_PROGRESS, HEARING_SCHEDULED, COMPENSATION_ASSESSMENT, COMPENSATION_APPROVED, PAYMENT_PROCESSING, PAYMENT_COMPLETED, CLOSED }
