package com.landportal.controller;
import com.landportal.entity.*; import com.landportal.repository.*; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/officer") public class ManagementController {final UserRepository users;final AcquisitionCaseRepository cases;final ParcelRepository parcels;final OwnershipRepository ownership;final CompensationRepository comps;final PaymentRepository payments;final HearingRepository hearings;final DocumentRepository docs;final GrievanceRepository grievances;final NotificationRepository notifications;
 public ManagementController(UserRepository u,AcquisitionCaseRepository c,ParcelRepository p,OwnershipRepository o,CompensationRepository cp,PaymentRepository pay,HearingRepository h,DocumentRepository d,GrievanceRepository g,NotificationRepository n){users=u;cases=c;parcels=p;ownership=o;comps=cp;payments=pay;hearings=h;docs=d;grievances=g;notifications=n;}
 private void officer(Long id){var u=users.findById(id).orElseThrow();if(u.getRole()!=Role.OFFICER&&u.getRole()!=Role.ADMIN)throw new RuntimeException("Officer only");}
 @PostMapping("/parcels") Parcel parcel(@RequestBody Parcel p){return parcels.save(p);}
 @PostMapping("/ownership") Ownership owner(@RequestParam Long userId,@RequestParam Long parcelId,@RequestParam double percentage){var o=new Ownership();o.setUser(users.findById(userId).orElseThrow());o.setParcel(parcels.findById(parcelId).orElseThrow());o.setOwnershipPercentage(percentage);return ownership.save(o);}
 @PostMapping("/cases") AcquisitionCase acase(@RequestBody AcquisitionCase c){if(c.getParcel()==null||c.getParcel().getId()==null)throw new RuntimeException("parcel.id required");c.setParcel(parcels.findById(c.getParcel().getId()).orElseThrow());return cases.save(c);}
 @PutMapping("/cases/{id}/compensation") Compensation comp(@PathVariable Long id,@RequestParam double assessedAmount,@RequestParam double approvedAmount,@RequestParam(defaultValue="APPROVED") String status){var c=cases.findById(id).orElseThrow();var x=comps.findByAcquisitionCaseId(id).orElse(new Compensation());x.setAcquisitionCase(c);x.setAssessedAmount(assessedAmount);x.setApprovedAmount(approvedAmount);x.setStatus(status);return comps.save(x);}
 @PostMapping("/cases/{id}/payments") Payment payment(@PathVariable Long id,@RequestParam double amount,@RequestParam String transactionReference,@RequestParam(defaultValue="PAID") PaymentStatus status){var c=comps.findByAcquisitionCaseId(id).orElseThrow();var p=new Payment();p.setCompensation(c);p.setAmount(amount);p.setTransactionReference(transactionReference);p.setStatus(status);if(status==PaymentStatus.PAID)p.setPaidAt(LocalDateTime.now());return payments.save(p);}
 @PostMapping("/cases/{id}/hearings") Hearing hearing(@PathVariable Long id,@RequestBody Hearing h){h.setAcquisitionCase(cases.findById(id).orElseThrow());return hearings.save(h);}
 @PutMapping("/hearings/{id}") Hearing updateHearing(@PathVariable Long id,@RequestBody Hearing input){var h=hearings.findById(id).orElseThrow();h.setHearingDate(input.getHearingDate());h.setLocation(input.getLocation());h.setStatus(input.getStatus());h.setRemarks(input.getRemarks());return hearings.save(h);}
 @PostMapping("/cases/{id}/documents") Document document(@PathVariable Long id,@RequestBody Document d,Authentication a){d.setAcquisitionCase(cases.findById(id).orElseThrow());d.setUploadedBy(users.findByEmail(a.getName()).orElseThrow());return docs.save(d);}
 @GetMapping("/grievances") List<Grievance> allGrievances(){return grievances.findAllByOrderByCreatedAtDesc();}
 @PutMapping("/grievances/{id}") Grievance grievance(@PathVariable Long id,@RequestParam GrievanceStatus status,@RequestParam(defaultValue="") String resolution){var g=grievances.findById(id).orElseThrow();g.setStatus(status);g.setResolution(resolution);if(status==GrievanceStatus.RESOLVED||status==GrievanceStatus.REJECTED)g.setResolvedAt(LocalDateTime.now());return grievances.save(g);}
}
